services:
  app:
    build:
      context: ../../app
      dockerfile: Dockerfile.prod
    container_name: promptly-web
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./data/uploads:/app/public/uploads

  db:
    image: mysql:8.0
    container_name: promptly-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    restart: unless-stopped

networks:
  default:
    name: promptly
